spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aishwarya14666/Configuration-properties.git
          clone-on-start: true
management:
  security:
    enabled: false