
0server:
  port: 9092
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
     # routes:
      #- id: one
      #  uri: lb://WELCOME-API
    #    predicates:
    #    - Path = /welcome
   #   - id: two
  #      uri: lb://GREET-API
  #      predicates:
   #     - Path = /greet
      routes:
        - id: first-microservice
          uri: http://localhost:8080/
          predicates:
            - Path=/welcome
        - id: second-microservice
          uri: http://localhost:9090/
          predicates:
            - Path=/greet
  main:
    web-application-type: reactive
            